/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountIdentifier,
    AccountIdentifierFromJSON,
    AccountIdentifierFromJSONTyped,
    AccountIdentifierToJSON,
    TokenAmount,
    TokenAmountFromJSON,
    TokenAmountFromJSONTyped,
    TokenAmountToJSON,
    TokenProperties,
    TokenPropertiesFromJSON,
    TokenPropertiesFromJSONTyped,
    TokenPropertiesToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateTokenDefinitionAllOf
 */
export interface CreateTokenDefinitionAllOf {
    /**
     * 
     * @type {TokenProperties}
     * @memberof CreateTokenDefinitionAllOf
     */
    tokenProperties: TokenProperties;
    /**
     * 
     * @type {TokenAmount}
     * @memberof CreateTokenDefinitionAllOf
     */
    tokenSupply: TokenAmount;
    /**
     * 
     * @type {AccountIdentifier}
     * @memberof CreateTokenDefinitionAllOf
     */
    to?: AccountIdentifier;
}

export function CreateTokenDefinitionAllOfFromJSON(json: any): CreateTokenDefinitionAllOf {
    return CreateTokenDefinitionAllOfFromJSONTyped(json, false);
}

export function CreateTokenDefinitionAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTokenDefinitionAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tokenProperties': TokenPropertiesFromJSON(json['token_properties']),
        'tokenSupply': TokenAmountFromJSON(json['token_supply']),
        'to': !exists(json, 'to') ? undefined : AccountIdentifierFromJSON(json['to']),
    };
}

export function CreateTokenDefinitionAllOfToJSON(value?: CreateTokenDefinitionAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token_properties': TokenPropertiesToJSON(value.tokenProperties),
        'token_supply': TokenAmountToJSON(value.tokenSupply),
        'to': AccountIdentifierToJSON(value.to),
    };
}

