/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TargetLedgerState
 */
export interface TargetLedgerState {
    /**
     * 
     * @type {number}
     * @memberof TargetLedgerState
     */
    version: number;
}

export function TargetLedgerStateFromJSON(json: any): TargetLedgerState {
    return TargetLedgerStateFromJSONTyped(json, false);
}

export function TargetLedgerStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TargetLedgerState {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': json['version'],
    };
}

export function TargetLedgerStateToJSON(value?: TargetLedgerState | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
    };
}

