/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TokenAmount,
    TokenAmountFromJSON,
    TokenAmountFromJSONTyped,
    TokenAmountToJSON,
} from './';

/**
 * 
 * @export
 * @interface TransactionRules
 */
export interface TransactionRules {
    /**
     * 
     * @type {number}
     * @memberof TransactionRules
     */
    maximumMessageLength?: number;
    /**
     * 
     * @type {TokenAmount}
     * @memberof TransactionRules
     */
    minimumStake?: TokenAmount;
}

export function TransactionRulesFromJSON(json: any): TransactionRules {
    return TransactionRulesFromJSONTyped(json, false);
}

export function TransactionRulesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionRules {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'maximumMessageLength': !exists(json, 'maximum_message_length') ? undefined : json['maximum_message_length'],
        'minimumStake': !exists(json, 'minimum_stake') ? undefined : TokenAmountFromJSON(json['minimum_stake']),
    };
}

export function TransactionRulesToJSON(value?: TransactionRules | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'maximum_message_length': value.maximumMessageLength,
        'minimum_stake': TokenAmountToJSON(value.minimumStake),
    };
}

