/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountUnstakesResponseUnstakes
 */
export interface AccountUnstakesResponseUnstakes {
    /**
     * 
     * @type {string}
     * @memberof AccountUnstakesResponseUnstakes
     */
    validatorAddress: string;
    /**
     * 
     * @type {string}
     * @memberof AccountUnstakesResponseUnstakes
     */
    amount: string;
    /**
     * 
     * @type {number}
     * @memberof AccountUnstakesResponseUnstakes
     */
    epochsUntil?: number;
}

export function AccountUnstakesResponseUnstakesFromJSON(json: any): AccountUnstakesResponseUnstakes {
    return AccountUnstakesResponseUnstakesFromJSONTyped(json, false);
}

export function AccountUnstakesResponseUnstakesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountUnstakesResponseUnstakes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'validatorAddress': json['validatorAddress'],
        'amount': json['amount'],
        'epochsUntil': !exists(json, 'epochsUntil') ? undefined : json['epochsUntil'],
    };
}

export function AccountUnstakesResponseUnstakesToJSON(value?: AccountUnstakesResponseUnstakes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'validatorAddress': value.validatorAddress,
        'amount': value.amount,
        'epochsUntil': value.epochsUntil,
    };
}

