/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountUnstakesResponseUnstakes,
    AccountUnstakesResponseUnstakesFromJSON,
    AccountUnstakesResponseUnstakesFromJSONTyped,
    AccountUnstakesResponseUnstakesToJSON,
} from './';

/**
 * 
 * @export
 * @interface AccountUnstakesResponse
 */
export interface AccountUnstakesResponse {
    /**
     * 
     * @type {Array<AccountUnstakesResponseUnstakes>}
     * @memberof AccountUnstakesResponse
     */
    unstakes: Array<AccountUnstakesResponseUnstakes>;
}

export function AccountUnstakesResponseFromJSON(json: any): AccountUnstakesResponse {
    return AccountUnstakesResponseFromJSONTyped(json, false);
}

export function AccountUnstakesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountUnstakesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'unstakes': ((json['unstakes'] as Array<any>).map(AccountUnstakesResponseUnstakesFromJSON)),
    };
}

export function AccountUnstakesResponseToJSON(value?: AccountUnstakesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'unstakes': ((value.unstakes as Array<any>).map(AccountUnstakesResponseUnstakesToJSON)),
    };
}

