/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountBalancesResponseBalances,
    AccountBalancesResponseBalancesFromJSON,
    AccountBalancesResponseBalancesFromJSONTyped,
    AccountBalancesResponseBalancesToJSON,
} from './';

/**
 * 
 * @export
 * @interface AccountBalancesResponse
 */
export interface AccountBalancesResponse {
    /**
     * 
     * @type {Array<AccountBalancesResponseBalances>}
     * @memberof AccountBalancesResponse
     */
    balances: Array<AccountBalancesResponseBalances>;
}

export function AccountBalancesResponseFromJSON(json: any): AccountBalancesResponse {
    return AccountBalancesResponseFromJSONTyped(json, false);
}

export function AccountBalancesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountBalancesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balances': ((json['balances'] as Array<any>).map(AccountBalancesResponseBalancesFromJSON)),
    };
}

export function AccountBalancesResponseToJSON(value?: AccountBalancesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balances': ((value.balances as Array<any>).map(AccountBalancesResponseBalancesToJSON)),
    };
}

