/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountBalancesResponseBalances
 */
export interface AccountBalancesResponseBalances {
    /**
     * 
     * @type {string}
     * @memberof AccountBalancesResponseBalances
     */
    rri: string;
    /**
     * 
     * @type {string}
     * @memberof AccountBalancesResponseBalances
     */
    amount: string;
}

export function AccountBalancesResponseBalancesFromJSON(json: any): AccountBalancesResponseBalances {
    return AccountBalancesResponseBalancesFromJSONTyped(json, false);
}

export function AccountBalancesResponseBalancesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountBalancesResponseBalances {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rri': json['rri'],
        'amount': json['amount'],
    };
}

export function AccountBalancesResponseBalancesToJSON(value?: AccountBalancesResponseBalances | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rri': value.rri,
        'amount': value.amount,
    };
}

