/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountStakesResponseStakes
 */
export interface AccountStakesResponseStakes {
    /**
     * 
     * @type {string}
     * @memberof AccountStakesResponseStakes
     */
    validatorAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountStakesResponseStakes
     */
    amount: string;
}

export function AccountStakesResponseStakesFromJSON(json: any): AccountStakesResponseStakes {
    return AccountStakesResponseStakesFromJSONTyped(json, false);
}

export function AccountStakesResponseStakesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountStakesResponseStakes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'validatorAddress': !exists(json, 'validatorAddress') ? undefined : json['validatorAddress'],
        'amount': json['amount'],
    };
}

export function AccountStakesResponseStakesToJSON(value?: AccountStakesResponseStakes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'validatorAddress': value.validatorAddress,
        'amount': value.amount,
    };
}

