/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CommittedTransaction,
    CommittedTransactionFromJSON,
    CommittedTransactionFromJSONTyped,
    CommittedTransactionToJSON,
} from './';

/**
 * 
 * @export
 * @interface AccountTransactionsResponse
 */
export interface AccountTransactionsResponse {
    /**
     * 
     * @type {number}
     * @memberof AccountTransactionsResponse
     */
    totalCount: number;
    /**
     * 
     * @type {number}
     * @memberof AccountTransactionsResponse
     */
    nextCursor?: number;
    /**
     * 
     * @type {Array<CommittedTransaction>}
     * @memberof AccountTransactionsResponse
     */
    transactions: Array<CommittedTransaction>;
}

export function AccountTransactionsResponseFromJSON(json: any): AccountTransactionsResponse {
    return AccountTransactionsResponseFromJSONTyped(json, false);
}

export function AccountTransactionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountTransactionsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'],
        'nextCursor': !exists(json, 'nextCursor') ? undefined : json['nextCursor'],
        'transactions': ((json['transactions'] as Array<any>).map(CommittedTransactionFromJSON)),
    };
}

export function AccountTransactionsResponseToJSON(value?: AccountTransactionsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalCount': value.totalCount,
        'nextCursor': value.nextCursor,
        'transactions': ((value.transactions as Array<any>).map(CommittedTransactionToJSON)),
    };
}

