/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommittedTransactionIdentifier
 */
export interface CommittedTransactionIdentifier {
    /**
     * 
     * @type {number}
     * @memberof CommittedTransactionIdentifier
     */
    stateVersion: number;
    /**
     * 
     * @type {string}
     * @memberof CommittedTransactionIdentifier
     */
    accumulator: string;
    /**
     * 
     * @type {string}
     * @memberof CommittedTransactionIdentifier
     */
    transactionIdentifier: string;
}

export function CommittedTransactionIdentifierFromJSON(json: any): CommittedTransactionIdentifier {
    return CommittedTransactionIdentifierFromJSONTyped(json, false);
}

export function CommittedTransactionIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommittedTransactionIdentifier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stateVersion': json['stateVersion'],
        'accumulator': json['accumulator'],
        'transactionIdentifier': json['transactionIdentifier'],
    };
}

export function CommittedTransactionIdentifierToJSON(value?: CommittedTransactionIdentifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stateVersion': value.stateVersion,
        'accumulator': value.accumulator,
        'transactionIdentifier': value.transactionIdentifier,
    };
}

