/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
     InternalServerErrorFromJSONTyped,
     InvalidJsonErrorFromJSONTyped,
     InvalidRequestErrorFromJSONTyped,
     InvalidTransactionErrorFromJSONTyped,
     MempoolErrorFromJSONTyped,
     StateConflictErrorFromJSONTyped
} from './';

/**
 * 
 * @export
 * @interface ConstructionSubmitUnexpectedError
 */
export interface ConstructionSubmitUnexpectedError {
    /**
     * 
     * @type {string}
     * @memberof ConstructionSubmitUnexpectedError
     */
    message: string;
}

export function ConstructionSubmitUnexpectedErrorFromJSON(json: any): ConstructionSubmitUnexpectedError {
    return ConstructionSubmitUnexpectedErrorFromJSONTyped(json, false);
}

export function ConstructionSubmitUnexpectedErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionSubmitUnexpectedError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['message'] === 'INTERNAL_SERVER_ERROR') {
            return InternalServerErrorFromJSONTyped(json, true);
        }
        if (json['message'] === 'INVALID_JSON') {
            return InvalidJsonErrorFromJSONTyped(json, true);
        }
        if (json['message'] === 'INVALID_REQUEST') {
            return InvalidRequestErrorFromJSONTyped(json, true);
        }
        if (json['message'] === 'INVALID_TRANSACTION') {
            return InvalidTransactionErrorFromJSONTyped(json, true);
        }
        if (json['message'] === 'MEMPOOL_FULL') {
            return MempoolErrorFromJSONTyped(json, true);
        }
        if (json['message'] === 'STATE_CONFLICT') {
            return StateConflictErrorFromJSONTyped(json, true);
        }
    }
    return {
        
        'message': json['message'],
    };
}

export function ConstructionSubmitUnexpectedErrorToJSON(value?: ConstructionSubmitUnexpectedError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

