/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConstructionBuildSuccessResponseAllOf
 */
export interface ConstructionBuildSuccessResponseAllOf {
    /**
     * 
     * @type {string}
     * @memberof ConstructionBuildSuccessResponseAllOf
     */
    fee: string;
    /**
     * 
     * @type {string}
     * @memberof ConstructionBuildSuccessResponseAllOf
     */
    unsignedTransaction: string;
    /**
     * 
     * @type {string}
     * @memberof ConstructionBuildSuccessResponseAllOf
     */
    payloadToSign: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof ConstructionBuildSuccessResponseAllOf
     */
    notifications: Array<object>;
}

export function ConstructionBuildSuccessResponseAllOfFromJSON(json: any): ConstructionBuildSuccessResponseAllOf {
    return ConstructionBuildSuccessResponseAllOfFromJSONTyped(json, false);
}

export function ConstructionBuildSuccessResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionBuildSuccessResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fee': json['fee'],
        'unsignedTransaction': json['unsignedTransaction'],
        'payloadToSign': json['payloadToSign'],
        'notifications': json['notifications'],
    };
}

export function ConstructionBuildSuccessResponseAllOfToJSON(value?: ConstructionBuildSuccessResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fee': value.fee,
        'unsignedTransaction': value.unsignedTransaction,
        'payloadToSign': value.payloadToSign,
        'notifications': value.notifications,
    };
}

