/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstructionFinalizeRequestSignature,
    ConstructionFinalizeRequestSignatureFromJSON,
    ConstructionFinalizeRequestSignatureFromJSONTyped,
    ConstructionFinalizeRequestSignatureToJSON,
} from './';

/**
 * 
 * @export
 * @interface ConstructionFinalizeRequest
 */
export interface ConstructionFinalizeRequest {
    /**
     * 
     * @type {string}
     * @memberof ConstructionFinalizeRequest
     */
    unsignedTransaction: string;
    /**
     * 
     * @type {ConstructionFinalizeRequestSignature}
     * @memberof ConstructionFinalizeRequest
     */
    signature: ConstructionFinalizeRequestSignature;
}

export function ConstructionFinalizeRequestFromJSON(json: any): ConstructionFinalizeRequest {
    return ConstructionFinalizeRequestFromJSONTyped(json, false);
}

export function ConstructionFinalizeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionFinalizeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'unsignedTransaction': json['unsignedTransaction'],
        'signature': ConstructionFinalizeRequestSignatureFromJSON(json['signature']),
    };
}

export function ConstructionFinalizeRequestToJSON(value?: ConstructionFinalizeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'unsignedTransaction': value.unsignedTransaction,
        'signature': ConstructionFinalizeRequestSignatureToJSON(value.signature),
    };
}

