/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConstructionBuildErrorAboveMaximumRakeIncrease
 */
export interface ConstructionBuildErrorAboveMaximumRakeIncrease {
    /**
     * 
     * @type {string}
     * @memberof ConstructionBuildErrorAboveMaximumRakeIncrease
     */
    limit?: string;
    /**
     * 
     * @type {string}
     * @memberof ConstructionBuildErrorAboveMaximumRakeIncrease
     */
    attempted?: string;
}

export function ConstructionBuildErrorAboveMaximumRakeIncreaseFromJSON(json: any): ConstructionBuildErrorAboveMaximumRakeIncrease {
    return ConstructionBuildErrorAboveMaximumRakeIncreaseFromJSONTyped(json, false);
}

export function ConstructionBuildErrorAboveMaximumRakeIncreaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionBuildErrorAboveMaximumRakeIncrease {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'attempted': !exists(json, 'attempted') ? undefined : json['attempted'],
    };
}

export function ConstructionBuildErrorAboveMaximumRakeIncreaseToJSON(value?: ConstructionBuildErrorAboveMaximumRakeIncrease | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'limit': value.limit,
        'attempted': value.attempted,
    };
}

