/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstructionBuildResponse,
    ConstructionBuildResponseFromJSON,
    ConstructionBuildResponseFromJSONTyped,
    ConstructionBuildResponseToJSON,
    ConstructionBuildSuccessResponseAllOf,
    ConstructionBuildSuccessResponseAllOfFromJSON,
    ConstructionBuildSuccessResponseAllOfFromJSONTyped,
    ConstructionBuildSuccessResponseAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface ConstructionBuildSuccessResponse
 */
export interface ConstructionBuildSuccessResponse extends ConstructionBuildResponse {
    /**
     * 
     * @type {string}
     * @memberof ConstructionBuildSuccessResponse
     */
    fee: string;
    /**
     * 
     * @type {string}
     * @memberof ConstructionBuildSuccessResponse
     */
    unsignedTransaction: string;
    /**
     * 
     * @type {string}
     * @memberof ConstructionBuildSuccessResponse
     */
    payloadToSign: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof ConstructionBuildSuccessResponse
     */
    notifications: Array<object>;
}

export function ConstructionBuildSuccessResponseFromJSON(json: any): ConstructionBuildSuccessResponse {
    return ConstructionBuildSuccessResponseFromJSONTyped(json, false);
}

export function ConstructionBuildSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionBuildSuccessResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ConstructionBuildResponseFromJSONTyped(json, ignoreDiscriminator),
        'fee': json['fee'],
        'unsignedTransaction': json['unsignedTransaction'],
        'payloadToSign': json['payloadToSign'],
        'notifications': json['notifications'],
    };
}

export function ConstructionBuildSuccessResponseToJSON(value?: ConstructionBuildSuccessResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ConstructionBuildResponseToJSON(value),
        'fee': value.fee,
        'unsignedTransaction': value.unsignedTransaction,
        'payloadToSign': value.payloadToSign,
        'notifications': value.notifications,
    };
}

