/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConstructionBuildErrorMessageTooLong
 */
export interface ConstructionBuildErrorMessageTooLong {
    /**
     * 
     * @type {number}
     * @memberof ConstructionBuildErrorMessageTooLong
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ConstructionBuildErrorMessageTooLong
     */
    actual: number;
}

export function ConstructionBuildErrorMessageTooLongFromJSON(json: any): ConstructionBuildErrorMessageTooLong {
    return ConstructionBuildErrorMessageTooLongFromJSONTyped(json, false);
}

export function ConstructionBuildErrorMessageTooLongFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionBuildErrorMessageTooLong {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'actual': json['actual'],
    };
}

export function ConstructionBuildErrorMessageTooLongToJSON(value?: ConstructionBuildErrorMessageTooLong | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'limit': value.limit,
        'actual': value.actual,
    };
}

