/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Action,
    ActionFromJSON,
    ActionFromJSONTyped,
    ActionToJSON,
} from './';

/**
 * 
 * @export
 * @interface ConstructionBuildRequest
 */
export interface ConstructionBuildRequest {
    /**
     * 
     * @type {Array<Action>}
     * @memberof ConstructionBuildRequest
     */
    actions: Array<Action>;
    /**
     * 
     * @type {string}
     * @memberof ConstructionBuildRequest
     */
    feePayer: string;
    /**
     * 
     * @type {string}
     * @memberof ConstructionBuildRequest
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConstructionBuildRequest
     */
    disableResourceAllocationAndDestroy?: boolean;
}

export function ConstructionBuildRequestFromJSON(json: any): ConstructionBuildRequest {
    return ConstructionBuildRequestFromJSONTyped(json, false);
}

export function ConstructionBuildRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionBuildRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actions': ((json['actions'] as Array<any>).map(ActionFromJSON)),
        'feePayer': json['feePayer'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'disableResourceAllocationAndDestroy': !exists(json, 'disableResourceAllocationAndDestroy') ? undefined : json['disableResourceAllocationAndDestroy'],
    };
}

export function ConstructionBuildRequestToJSON(value?: ConstructionBuildRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actions': ((value.actions as Array<any>).map(ActionToJSON)),
        'feePayer': value.feePayer,
        'message': value.message,
        'disableResourceAllocationAndDestroy': value.disableResourceAllocationAndDestroy,
    };
}

