/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConstructionFinalizeResponse
 */
export interface ConstructionFinalizeResponse {
    /**
     * 
     * @type {string}
     * @memberof ConstructionFinalizeResponse
     */
    signedTransaction: string;
}

export function ConstructionFinalizeResponseFromJSON(json: any): ConstructionFinalizeResponse {
    return ConstructionFinalizeResponseFromJSONTyped(json, false);
}

export function ConstructionFinalizeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionFinalizeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'signedTransaction': json['signedTransaction'],
    };
}

export function ConstructionFinalizeResponseToJSON(value?: ConstructionFinalizeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'signedTransaction': value.signedTransaction,
    };
}

