/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConstructionBuildErrorCouldNotConstructFees
 */
export interface ConstructionBuildErrorCouldNotConstructFees {
    /**
     * 
     * @type {number}
     * @memberof ConstructionBuildErrorCouldNotConstructFees
     */
    attempts?: number;
}

export function ConstructionBuildErrorCouldNotConstructFeesFromJSON(json: any): ConstructionBuildErrorCouldNotConstructFees {
    return ConstructionBuildErrorCouldNotConstructFeesFromJSONTyped(json, false);
}

export function ConstructionBuildErrorCouldNotConstructFeesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionBuildErrorCouldNotConstructFees {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attempts': !exists(json, 'attempts') ? undefined : json['attempts'],
    };
}

export function ConstructionBuildErrorCouldNotConstructFeesToJSON(value?: ConstructionBuildErrorCouldNotConstructFees | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attempts': value.attempts,
    };
}

