/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
     ConstructionBuildErrorResponseFromJSONTyped,
     ConstructionBuildSuccessResponseFromJSONTyped
} from './';

/**
 * 
 * @export
 * @interface ConstructionBuildResponse
 */
export interface ConstructionBuildResponse {
    /**
     * 
     * @type {string}
     * @memberof ConstructionBuildResponse
     */
    result: string;
}

export function ConstructionBuildResponseFromJSON(json: any): ConstructionBuildResponse {
    return ConstructionBuildResponseFromJSONTyped(json, false);
}

export function ConstructionBuildResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionBuildResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['result'] === 'error') {
            return ConstructionBuildErrorResponseFromJSONTyped(json, true);
        }
        if (json['result'] === 'success') {
            return ConstructionBuildSuccessResponseFromJSONTyped(json, true);
        }
    }
    return {
        
        'result': json['result'],
    };
}

export function ConstructionBuildResponseToJSON(value?: ConstructionBuildResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
    };
}

