/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstructionBuildError,
    ConstructionBuildErrorFromJSON,
    ConstructionBuildErrorFromJSONTyped,
    ConstructionBuildErrorToJSON,
} from './';

/**
 * 
 * @export
 * @interface ConstructionBuildErrorResponseAllOf
 */
export interface ConstructionBuildErrorResponseAllOf {
    /**
     * 
     * @type {ConstructionBuildError}
     * @memberof ConstructionBuildErrorResponseAllOf
     */
    details: ConstructionBuildError;
}

export function ConstructionBuildErrorResponseAllOfFromJSON(json: any): ConstructionBuildErrorResponseAllOf {
    return ConstructionBuildErrorResponseAllOfFromJSONTyped(json, false);
}

export function ConstructionBuildErrorResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionBuildErrorResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'details': ConstructionBuildErrorFromJSON(json['details']),
    };
}

export function ConstructionBuildErrorResponseAllOfToJSON(value?: ConstructionBuildErrorResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'details': ConstructionBuildErrorToJSON(value.details),
    };
}

