/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConstructionBuildError,
    ConstructionBuildErrorFromJSON,
    ConstructionBuildErrorFromJSONTyped,
    ConstructionBuildErrorToJSON,
    ConstructionBuildErrorResponseAllOf,
    ConstructionBuildErrorResponseAllOfFromJSON,
    ConstructionBuildErrorResponseAllOfFromJSONTyped,
    ConstructionBuildErrorResponseAllOfToJSON,
    ConstructionBuildResponse,
    ConstructionBuildResponseFromJSON,
    ConstructionBuildResponseFromJSONTyped,
    ConstructionBuildResponseToJSON,
} from './';

/**
 * 
 * @export
 * @interface ConstructionBuildErrorResponse
 */
export interface ConstructionBuildErrorResponse extends ConstructionBuildResponse {
    /**
     * 
     * @type {ConstructionBuildError}
     * @memberof ConstructionBuildErrorResponse
     */
    details: ConstructionBuildError;
}

export function ConstructionBuildErrorResponseFromJSON(json: any): ConstructionBuildErrorResponse {
    return ConstructionBuildErrorResponseFromJSONTyped(json, false);
}

export function ConstructionBuildErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionBuildErrorResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ConstructionBuildResponseFromJSONTyped(json, ignoreDiscriminator),
        'details': ConstructionBuildErrorFromJSON(json['details']),
    };
}

export function ConstructionBuildErrorResponseToJSON(value?: ConstructionBuildErrorResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ConstructionBuildResponseToJSON(value),
        'details': ConstructionBuildErrorToJSON(value.details),
    };
}

