/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConstructionBuildErrorNotEnoughResources
 */
export interface ConstructionBuildErrorNotEnoughResources {
    /**
     * 
     * @type {string}
     * @memberof ConstructionBuildErrorNotEnoughResources
     */
    requested: string;
    /**
     * 
     * @type {string}
     * @memberof ConstructionBuildErrorNotEnoughResources
     */
    available: string;
}

export function ConstructionBuildErrorNotEnoughResourcesFromJSON(json: any): ConstructionBuildErrorNotEnoughResources {
    return ConstructionBuildErrorNotEnoughResourcesFromJSONTyped(json, false);
}

export function ConstructionBuildErrorNotEnoughResourcesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionBuildErrorNotEnoughResources {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requested': json['requested'],
        'available': json['available'],
    };
}

export function ConstructionBuildErrorNotEnoughResourcesToJSON(value?: ConstructionBuildErrorNotEnoughResources | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'requested': value.requested,
        'available': value.available,
    };
}

