/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvalidTransactionError
 */
export interface InvalidTransactionError {
    /**
     * 
     * @type {string}
     * @memberof InvalidTransactionError
     */
    message?: string;
}

export function InvalidTransactionErrorFromJSON(json: any): InvalidTransactionError {
    return InvalidTransactionErrorFromJSONTyped(json, false);
}

export function InvalidTransactionErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvalidTransactionError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function InvalidTransactionErrorToJSON(value?: InvalidTransactionError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

