/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Network,
    NetworkFromJSON,
    NetworkFromJSONTyped,
    NetworkToJSON,
} from './';

/**
 * 
 * @export
 * @interface NetworkResponse
 */
export interface NetworkResponse {
    /**
     * 
     * @type {Network}
     * @memberof NetworkResponse
     */
    network: Network;
}

export function NetworkResponseFromJSON(json: any): NetworkResponse {
    return NetworkResponseFromJSONTyped(json, false);
}

export function NetworkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'network': NetworkFromJSON(json['network']),
    };
}

export function NetworkResponseToJSON(value?: NetworkResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'network': NetworkToJSON(value.network),
    };
}

