/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TokenAmount,
    TokenAmountFromJSON,
    TokenAmountFromJSONTyped,
    TokenAmountToJSON,
    VaultIdentifier,
    VaultIdentifierFromJSON,
    VaultIdentifierFromJSONTyped,
    VaultIdentifierToJSON,
} from './';

/**
 * 
 * @export
 * @interface Operation
 */
export interface Operation {
    /**
     * 
     * @type {VaultIdentifier}
     * @memberof Operation
     */
    vaultIdentifier?: VaultIdentifier;
    /**
     * 
     * @type {TokenAmount}
     * @memberof Operation
     */
    amount?: TokenAmount;
}

export function OperationFromJSON(json: any): Operation {
    return OperationFromJSONTyped(json, false);
}

export function OperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Operation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'vaultIdentifier': !exists(json, 'vaultIdentifier') ? undefined : VaultIdentifierFromJSON(json['vaultIdentifier']),
        'amount': !exists(json, 'amount') ? undefined : TokenAmountFromJSON(json['amount']),
    };
}

export function OperationToJSON(value?: Operation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'vaultIdentifier': VaultIdentifierToJSON(value.vaultIdentifier),
        'amount': TokenAmountToJSON(value.amount),
    };
}

