/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreparedStakeVault
 */
export interface PreparedStakeVault {
    /**
     * 
     * @type {string}
     * @memberof PreparedStakeVault
     */
    owner?: string;
    /**
     * 
     * @type {string}
     * @memberof PreparedStakeVault
     */
    validator?: string;
}

export function PreparedStakeVaultFromJSON(json: any): PreparedStakeVault {
    return PreparedStakeVaultFromJSONTyped(json, false);
}

export function PreparedStakeVaultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreparedStakeVault {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'owner': !exists(json, 'owner') ? undefined : json['owner'],
        'validator': !exists(json, 'validator') ? undefined : json['validator'],
    };
}

export function PreparedStakeVaultToJSON(value?: PreparedStakeVault | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'owner': value.owner,
        'validator': value.validator,
    };
}

