/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Action,
    ActionFromJSON,
    ActionFromJSONTyped,
    ActionToJSON,
    StakeTokensAllOf,
    StakeTokensAllOfFromJSON,
    StakeTokensAllOfFromJSONTyped,
    StakeTokensAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface StakeTokens
 */
export interface StakeTokens extends Action {
    /**
     * 
     * @type {string}
     * @memberof StakeTokens
     */
    from?: string;
    /**
     * 
     * @type {string}
     * @memberof StakeTokens
     */
    validator?: string;
    /**
     * 
     * @type {string}
     * @memberof StakeTokens
     */
    amount?: string;
}

export function StakeTokensFromJSON(json: any): StakeTokens {
    return StakeTokensFromJSONTyped(json, false);
}

export function StakeTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakeTokens {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ActionFromJSONTyped(json, ignoreDiscriminator),
        'from': !exists(json, 'from') ? undefined : json['from'],
        'validator': !exists(json, 'validator') ? undefined : json['validator'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
    };
}

export function StakeTokensToJSON(value?: StakeTokens | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ActionToJSON(value),
        'from': value.from,
        'validator': value.validator,
        'amount': value.amount,
    };
}

