/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StakeVault
 */
export interface StakeVault {
    /**
     * 
     * @type {string}
     * @memberof StakeVault
     */
    validator?: string;
}

export function StakeVaultFromJSON(json: any): StakeVault {
    return StakeVaultFromJSONTyped(json, false);
}

export function StakeVaultFromJSONTyped(json: any, ignoreDiscriminator: boolean): StakeVault {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'validator': !exists(json, 'validator') ? undefined : json['validator'],
    };
}

export function StakeVaultToJSON(value?: StakeVault | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'validator': value.validator,
    };
}

