/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenAccounting
 */
export interface TokenAccounting {
    /**
     * 
     * @type {string}
     * @memberof TokenAccounting
     */
    currentSupply: string;
    /**
     * 
     * @type {string}
     * @memberof TokenAccounting
     */
    totalMinted: string;
    /**
     * 
     * @type {string}
     * @memberof TokenAccounting
     */
    totalBurned: string;
}

export function TokenAccountingFromJSON(json: any): TokenAccounting {
    return TokenAccountingFromJSONTyped(json, false);
}

export function TokenAccountingFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenAccounting {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currentSupply': json['currentSupply'],
        'totalMinted': json['totalMinted'],
        'totalBurned': json['totalBurned'],
    };
}

export function TokenAccountingToJSON(value?: TokenAccounting | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currentSupply': value.currentSupply,
        'totalMinted': value.totalMinted,
        'totalBurned': value.totalBurned,
    };
}

