/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenProperties
 */
export interface TokenProperties {
    /**
     * 
     * @type {string}
     * @memberof TokenProperties
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TokenProperties
     */
    rri: string;
    /**
     * 
     * @type {string}
     * @memberof TokenProperties
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof TokenProperties
     */
    iconUrl: string;
    /**
     * 
     * @type {string}
     * @memberof TokenProperties
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof TokenProperties
     */
    symbol: string;
    /**
     * 
     * @type {boolean}
     * @memberof TokenProperties
     */
    isSupplyMutable: boolean;
    /**
     * 
     * @type {string}
     * @memberof TokenProperties
     */
    granularity: string;
}

export function TokenPropertiesFromJSON(json: any): TokenProperties {
    return TokenPropertiesFromJSONTyped(json, false);
}

export function TokenPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'rri': json['rri'],
        'description': json['description'],
        'iconUrl': json['iconUrl'],
        'url': json['url'],
        'symbol': json['symbol'],
        'isSupplyMutable': json['isSupplyMutable'],
        'granularity': json['granularity'],
    };
}

export function TokenPropertiesToJSON(value?: TokenProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'rri': value.rri,
        'description': value.description,
        'iconUrl': value.iconUrl,
        'url': value.url,
        'symbol': value.symbol,
        'isSupplyMutable': value.isSupplyMutable,
        'granularity': value.granularity,
    };
}

