/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenTransferAllOf
 */
export interface TokenTransferAllOf {
    /**
     * 
     * @type {string}
     * @memberof TokenTransferAllOf
     */
    from?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenTransferAllOf
     */
    to?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenTransferAllOf
     */
    amount?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenTransferAllOf
     */
    rri?: string;
}

export function TokenTransferAllOfFromJSON(json: any): TokenTransferAllOf {
    return TokenTransferAllOfFromJSONTyped(json, false);
}

export function TokenTransferAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenTransferAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': !exists(json, 'from') ? undefined : json['from'],
        'to': !exists(json, 'to') ? undefined : json['to'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'rri': !exists(json, 'rri') ? undefined : json['rri'],
    };
}

export function TokenTransferAllOfToJSON(value?: TokenTransferAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': value.from,
        'to': value.to,
        'amount': value.amount,
        'rri': value.rri,
    };
}

