/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CommittedTransaction,
    CommittedTransactionFromJSON,
    CommittedTransactionFromJSONTyped,
    CommittedTransactionToJSON,
} from './';

/**
 * 
 * @export
 * @interface TransactionInfoResponse
 */
export interface TransactionInfoResponse {
    /**
     * 
     * @type {Array<CommittedTransaction>}
     * @memberof TransactionInfoResponse
     */
    transaction: Array<CommittedTransaction>;
}

export function TransactionInfoResponseFromJSON(json: any): TransactionInfoResponse {
    return TransactionInfoResponseFromJSONTyped(json, false);
}

export function TransactionInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transaction': ((json['transaction'] as Array<any>).map(CommittedTransactionFromJSON)),
    };
}

export function TransactionInfoResponseToJSON(value?: TransactionInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transaction': ((value.transaction as Array<any>).map(CommittedTransactionToJSON)),
    };
}

