/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionInfoRequest
 */
export interface TransactionInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof TransactionInfoRequest
     */
    transactionIdentifier: string;
}

export function TransactionInfoRequestFromJSON(json: any): TransactionInfoRequest {
    return TransactionInfoRequestFromJSONTyped(json, false);
}

export function TransactionInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionInfoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transactionIdentifier': json['transactionIdentifier'],
    };
}

export function TransactionInfoRequestToJSON(value?: TransactionInfoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transactionIdentifier': value.transactionIdentifier,
    };
}

