/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Validator,
    ValidatorFromJSON,
    ValidatorFromJSONTyped,
    ValidatorToJSON,
} from './';

/**
 * 
 * @export
 * @interface ValidatorInfoResponse
 */
export interface ValidatorInfoResponse {
    /**
     * 
     * @type {Validator}
     * @memberof ValidatorInfoResponse
     */
    validator?: Validator;
}

export function ValidatorInfoResponseFromJSON(json: any): ValidatorInfoResponse {
    return ValidatorInfoResponseFromJSONTyped(json, false);
}

export function ValidatorInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatorInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'validator': !exists(json, 'validator') ? undefined : ValidatorFromJSON(json['validator']),
    };
}

export function ValidatorInfoResponseToJSON(value?: ValidatorInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'validator': ValidatorToJSON(value.validator),
    };
}

