/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidatorsRequest
 */
export interface ValidatorsRequest {
    /**
     * 
     * @type {number}
     * @memberof ValidatorsRequest
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ValidatorsRequest
     */
    offset?: number;
}

export function ValidatorsRequestFromJSON(json: any): ValidatorsRequest {
    return ValidatorsRequestFromJSONTyped(json, false);
}

export function ValidatorsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatorsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
    };
}

export function ValidatorsRequestToJSON(value?: ValidatorsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'limit': value.limit,
        'offset': value.offset,
    };
}

