/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidatorInfoRequest
 */
export interface ValidatorInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof ValidatorInfoRequest
     */
    validatorIdentifier: string;
}

export function ValidatorInfoRequestFromJSON(json: any): ValidatorInfoRequest {
    return ValidatorInfoRequestFromJSONTyped(json, false);
}

export function ValidatorInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatorInfoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'validatorIdentifier': json['validatorIdentifier'],
    };
}

export function ValidatorInfoRequestToJSON(value?: ValidatorInfoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'validatorIdentifier': value.validatorIdentifier,
    };
}

