/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidatorProperties
 */
export interface ValidatorProperties {
    /**
     * 
     * @type {string}
     * @memberof ValidatorProperties
     */
    validatorAddress: string;
    /**
     * 
     * @type {string}
     * @memberof ValidatorProperties
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof ValidatorProperties
     */
    validatorFee: string;
    /**
     * 
     * @type {string}
     * @memberof ValidatorProperties
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof ValidatorProperties
     */
    registered: boolean;
    /**
     * 
     * @type {string}
     * @memberof ValidatorProperties
     */
    ownerAddress: string;
    /**
     * 
     * @type {boolean}
     * @memberof ValidatorProperties
     */
    externalStakeAccepted: boolean;
}

export function ValidatorPropertiesFromJSON(json: any): ValidatorProperties {
    return ValidatorPropertiesFromJSONTyped(json, false);
}

export function ValidatorPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatorProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'validatorAddress': json['validatorAddress'],
        'url': json['url'],
        'validatorFee': json['validatorFee'],
        'name': json['name'],
        'registered': json['registered'],
        'ownerAddress': json['ownerAddress'],
        'externalStakeAccepted': json['externalStakeAccepted'],
    };
}

export function ValidatorPropertiesToJSON(value?: ValidatorProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'validatorAddress': value.validatorAddress,
        'url': value.url,
        'validatorFee': value.validatorFee,
        'name': value.name,
        'registered': value.registered,
        'ownerAddress': value.ownerAddress,
        'externalStakeAccepted': value.externalStakeAccepted,
    };
}

