/* tslint:disable */
/* eslint-disable */
/**
 * Wallet/Explorer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidatorStake
 */
export interface ValidatorStake {
    /**
     * 
     * @type {string}
     * @memberof ValidatorStake
     */
    exitingOwnership: string;
    /**
     * 
     * @type {string}
     * @memberof ValidatorStake
     */
    currentOwnership: string;
    /**
     * 
     * @type {string}
     * @memberof ValidatorStake
     */
    currentStake: string;
    /**
     * 
     * @type {string}
     * @memberof ValidatorStake
     */
    preparedStake: string;
    /**
     * 
     * @type {string}
     * @memberof ValidatorStake
     */
    nextEpochEstimatedStake: string;
    /**
     * 
     * @type {string}
     * @memberof ValidatorStake
     */
    nextEpochEstimatedOwnerStake: string;
}

export function ValidatorStakeFromJSON(json: any): ValidatorStake {
    return ValidatorStakeFromJSONTyped(json, false);
}

export function ValidatorStakeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatorStake {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'exitingOwnership': json['exitingOwnership'],
        'currentOwnership': json['currentOwnership'],
        'currentStake': json['currentStake'],
        'preparedStake': json['preparedStake'],
        'nextEpochEstimatedStake': json['nextEpochEstimatedStake'],
        'nextEpochEstimatedOwnerStake': json['nextEpochEstimatedOwnerStake'],
    };
}

export function ValidatorStakeToJSON(value?: ValidatorStake | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exitingOwnership': value.exitingOwnership,
        'currentOwnership': value.currentOwnership,
        'currentStake': value.currentStake,
        'preparedStake': value.preparedStake,
        'nextEpochEstimatedStake': value.nextEpochEstimatedStake,
        'nextEpochEstimatedOwnerStake': value.nextEpochEstimatedOwnerStake,
    };
}

