/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountTransactionStatus {
    'status': AccountTransactionStatus.StatusEnum;
    'confirmedTime'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "AccountTransactionStatus.StatusEnum"
        },
        {
            "name": "confirmedTime",
            "baseName": "confirmed_time",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountTransactionStatus.attributeTypeMap;
    }
}

export namespace AccountTransactionStatus {
    export enum StatusEnum {
        Pending = <any> 'PENDING',
        Confirmed = <any> 'CONFIRMED',
        Failed = <any> 'FAILED'
    }
}
