/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountIdentifier } from './accountIdentifier';
import { TokenAmount } from './tokenAmount';
import { TokenProperties } from './tokenProperties';

export class CreateTokenDefinitionAllOf {
    'tokenProperties': TokenProperties;
    'tokenSupply': TokenAmount;
    'to'?: AccountIdentifier;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tokenProperties",
            "baseName": "token_properties",
            "type": "TokenProperties"
        },
        {
            "name": "tokenSupply",
            "baseName": "token_supply",
            "type": "TokenAmount"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "AccountIdentifier"
        }    ];

    static getAttributeTypeMap() {
        return CreateTokenDefinitionAllOf.attributeTypeMap;
    }
}

