/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class LedgerState {
    'version': number;
    'timestamp': string;
    'epoch': number;
    'round': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string"
        },
        {
            "name": "epoch",
            "baseName": "epoch",
            "type": "number"
        },
        {
            "name": "round",
            "baseName": "round",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return LedgerState.attributeTypeMap;
    }
}

