/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class NotEnoughResourcesErrorAllOf {
    'requestedAmount': string;
    'availableAmount': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "requestedAmount",
            "baseName": "requested_amount",
            "type": "string"
        },
        {
            "name": "availableAmount",
            "baseName": "available_amount",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return NotEnoughResourcesErrorAllOf.attributeTypeMap;
    }
}

