/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountIdentifier } from './accountIdentifier';

export class TokenProperties {
    'name': string;
    'description': string;
    'iconUrl': string;
    'url': string;
    'symbol': string;
    'isSupplyMutable': boolean;
    'granularity': string;
    'owner'?: AccountIdentifier;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "iconUrl",
            "baseName": "icon_url",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string"
        },
        {
            "name": "isSupplyMutable",
            "baseName": "is_supply_mutable",
            "type": "boolean"
        },
        {
            "name": "granularity",
            "baseName": "granularity",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "AccountIdentifier"
        }    ];

    static getAttributeTypeMap() {
        return TokenProperties.attributeTypeMap;
    }
}

