/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TokenAmount } from './tokenAmount';
import { TokenIdentifier } from './tokenIdentifier';
import { TokenInfo } from './tokenInfo';
import { TokenProperties } from './tokenProperties';

export class Token {
    'tokenIdentifier': TokenIdentifier;
    'tokenSupply': TokenAmount;
    'info': TokenInfo;
    'tokenProperties': TokenProperties;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tokenIdentifier",
            "baseName": "token_identifier",
            "type": "TokenIdentifier"
        },
        {
            "name": "tokenSupply",
            "baseName": "token_supply",
            "type": "TokenAmount"
        },
        {
            "name": "info",
            "baseName": "info",
            "type": "TokenInfo"
        },
        {
            "name": "tokenProperties",
            "baseName": "token_properties",
            "type": "TokenProperties"
        }    ];

    static getAttributeTypeMap() {
        return Token.attributeTypeMap;
    }
}

