/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TokenAmount } from './tokenAmount';

export class TransactionRules {
    'maximumMessageLength'?: number;
    'minimumStake'?: TokenAmount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "maximumMessageLength",
            "baseName": "maximum_message_length",
            "type": "number"
        },
        {
            "name": "minimumStake",
            "baseName": "minimum_stake",
            "type": "TokenAmount"
        }    ];

    static getAttributeTypeMap() {
        return TransactionRules.attributeTypeMap;
    }
}

