/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransactionIdentifier } from './transactionIdentifier';

export class TransactionFinalizeResponse {
    'signedTransaction': string;
    'transactionIdentifier': TransactionIdentifier;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "signedTransaction",
            "baseName": "signed_transaction",
            "type": "string"
        },
        {
            "name": "transactionIdentifier",
            "baseName": "transaction_identifier",
            "type": "TransactionIdentifier"
        }    ];

    static getAttributeTypeMap() {
        return TransactionFinalizeResponse.attributeTypeMap;
    }
}

