/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransactionFinalizeRequestSignature } from './transactionFinalizeRequestSignature';

export class TransactionFinalizeRequest {
    'network': string;
    'unsignedTransaction': string;
    'signature': TransactionFinalizeRequestSignature;
    'submit'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "network",
            "baseName": "network",
            "type": "string"
        },
        {
            "name": "unsignedTransaction",
            "baseName": "unsigned_transaction",
            "type": "string"
        },
        {
            "name": "signature",
            "baseName": "signature",
            "type": "TransactionFinalizeRequestSignature"
        },
        {
            "name": "submit",
            "baseName": "submit",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return TransactionFinalizeRequest.attributeTypeMap;
    }
}

