/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountIdentifier } from './accountIdentifier';
import { Action } from './action';

export class TransactionBuildRequest {
    'network': string;
    'actions': Array<Action>;
    'feePayer': AccountIdentifier;
    'message'?: string;
    'disableTokenMintAndBurn'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "network",
            "baseName": "network",
            "type": "string"
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<Action>"
        },
        {
            "name": "feePayer",
            "baseName": "fee_payer",
            "type": "AccountIdentifier"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "disableTokenMintAndBurn",
            "baseName": "disable_token_mint_and_burn",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return TransactionBuildRequest.attributeTypeMap;
    }
}

