/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransactionBuildError } from './transactionBuildError';
import { TransactionBuildResponse } from './transactionBuildResponse';
import { TransactionBuildResponseErrorAllOf } from './transactionBuildResponseErrorAllOf';

export class TransactionBuildResponseError extends TransactionBuildResponse {
    'error': TransactionBuildError;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "TransactionBuildError"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(TransactionBuildResponseError.attributeTypeMap);
    }
}

