/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LedgerState } from './ledgerState';
import { Validator } from './validator';

export class ValidatorInfoResponse {
    'ledgerState': LedgerState;
    'validator': Validator;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ledgerState",
            "baseName": "ledger_state",
            "type": "LedgerState"
        },
        {
            "name": "validator",
            "baseName": "validator",
            "type": "Validator"
        }    ];

    static getAttributeTypeMap() {
        return ValidatorInfoResponse.attributeTypeMap;
    }
}

