/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TokenAmount } from './tokenAmount';
import { ValidatorIdentifier } from './validatorIdentifier';
import { ValidatorInfo } from './validatorInfo';
import { ValidatorProperties } from './validatorProperties';

export class Validator {
    'validatorIdentifier': ValidatorIdentifier;
    'stake': TokenAmount;
    'info': ValidatorInfo;
    'properties': ValidatorProperties;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "validatorIdentifier",
            "baseName": "validator_identifier",
            "type": "ValidatorIdentifier"
        },
        {
            "name": "stake",
            "baseName": "stake",
            "type": "TokenAmount"
        },
        {
            "name": "info",
            "baseName": "info",
            "type": "ValidatorInfo"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "ValidatorProperties"
        }    ];

    static getAttributeTypeMap() {
        return Validator.attributeTypeMap;
    }
}

