/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TokenAmount,
    TokenAmountFromJSON,
    TokenAmountFromJSONTyped,
    TokenAmountToJSON,
} from './';

/**
 * 
 * @export
 * @interface AccountStakeEntry
 */
export interface AccountStakeEntry {
    /**
     * 
     * @type {string}
     * @memberof AccountStakeEntry
     */
    validatorAddress: string;
    /**
     * 
     * @type {TokenAmount}
     * @memberof AccountStakeEntry
     */
    delegatedStake: TokenAmount;
}

export function AccountStakeEntryFromJSON(json: any): AccountStakeEntry {
    return AccountStakeEntryFromJSONTyped(json, false);
}

export function AccountStakeEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountStakeEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'validatorAddress': json['validator_address'],
        'delegatedStake': TokenAmountFromJSON(json['delegated_stake']),
    };
}

export function AccountStakeEntryToJSON(value?: AccountStakeEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'validator_address': value.validatorAddress,
        'delegated_stake': TokenAmountToJSON(value.delegatedStake),
    };
}

