/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountTransactionStatus
 */
export interface AccountTransactionStatus {
    /**
     * 
     * @type {string}
     * @memberof AccountTransactionStatus
     */
    status: AccountTransactionStatusStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof AccountTransactionStatus
     */
    confirmedTime?: string;
}

/**
* @export
* @enum {string}
*/
export enum AccountTransactionStatusStatusEnum {
    Mempool = 'MEMPOOL',
    Confirmed = 'CONFIRMED',
    Failed = 'FAILED'
}

export function AccountTransactionStatusFromJSON(json: any): AccountTransactionStatus {
    return AccountTransactionStatusFromJSONTyped(json, false);
}

export function AccountTransactionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountTransactionStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'confirmedTime': !exists(json, 'confirmed_time') ? undefined : json['confirmed_time'],
    };
}

export function AccountTransactionStatusToJSON(value?: AccountTransactionStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'confirmed_time': value.confirmedTime,
    };
}

