/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BelowMinimumStakeErrorAllOf
 */
export interface BelowMinimumStakeErrorAllOf {
    /**
     * 
     * @type {string}
     * @memberof BelowMinimumStakeErrorAllOf
     */
    requestedAmount: string;
    /**
     * 
     * @type {string}
     * @memberof BelowMinimumStakeErrorAllOf
     */
    minimumAmount: string;
}

export function BelowMinimumStakeErrorAllOfFromJSON(json: any): BelowMinimumStakeErrorAllOf {
    return BelowMinimumStakeErrorAllOfFromJSONTyped(json, false);
}

export function BelowMinimumStakeErrorAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): BelowMinimumStakeErrorAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestedAmount': json['requested_amount'],
        'minimumAmount': json['minimum_amount'],
    };
}

export function BelowMinimumStakeErrorAllOfToJSON(value?: BelowMinimumStakeErrorAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'requested_amount': value.requestedAmount,
        'minimum_amount': value.minimumAmount,
    };
}

