/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConstructionSubmitRequest
 */
export interface ConstructionSubmitRequest {
    /**
     * 
     * @type {string}
     * @memberof ConstructionSubmitRequest
     */
    network: string;
    /**
     * 
     * @type {string}
     * @memberof ConstructionSubmitRequest
     */
    signedTransaction: string;
}

export function ConstructionSubmitRequestFromJSON(json: any): ConstructionSubmitRequest {
    return ConstructionSubmitRequestFromJSONTyped(json, false);
}

export function ConstructionSubmitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionSubmitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'network': json['network'],
        'signedTransaction': json['signed_transaction'],
    };
}

export function ConstructionSubmitRequestToJSON(value?: ConstructionSubmitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'network': value.network,
        'signed_transaction': value.signedTransaction,
    };
}

