/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConstructionSubmitResponse
 */
export interface ConstructionSubmitResponse {
    /**
     * 
     * @type {string}
     * @memberof ConstructionSubmitResponse
     */
    transactionIdentifier: string;
}

export function ConstructionSubmitResponseFromJSON(json: any): ConstructionSubmitResponse {
    return ConstructionSubmitResponseFromJSONTyped(json, false);
}

export function ConstructionSubmitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionSubmitResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transactionIdentifier': json['transaction_identifier'],
    };
}

export function ConstructionSubmitResponseToJSON(value?: ConstructionSubmitResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transaction_identifier': value.transactionIdentifier,
    };
}

