/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotEnoughResourcesErrorAllOf
 */
export interface NotEnoughResourcesErrorAllOf {
    /**
     * 
     * @type {string}
     * @memberof NotEnoughResourcesErrorAllOf
     */
    requestedAmount: string;
    /**
     * 
     * @type {string}
     * @memberof NotEnoughResourcesErrorAllOf
     */
    availableAmount: string;
}

export function NotEnoughResourcesErrorAllOfFromJSON(json: any): NotEnoughResourcesErrorAllOf {
    return NotEnoughResourcesErrorAllOfFromJSONTyped(json, false);
}

export function NotEnoughResourcesErrorAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotEnoughResourcesErrorAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestedAmount': json['requested_amount'],
        'availableAmount': json['available_amount'],
    };
}

export function NotEnoughResourcesErrorAllOfToJSON(value?: NotEnoughResourcesErrorAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'requested_amount': value.requestedAmount,
        'available_amount': value.availableAmount,
    };
}

