/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenDeriveRequest
 */
export interface TokenDeriveRequest {
    /**
     * 
     * @type {string}
     * @memberof TokenDeriveRequest
     */
    network: string;
    /**
     * 
     * @type {string}
     * @memberof TokenDeriveRequest
     */
    creatorAccountAddress: string;
    /**
     * 
     * @type {string}
     * @memberof TokenDeriveRequest
     */
    symbol: string;
}

export function TokenDeriveRequestFromJSON(json: any): TokenDeriveRequest {
    return TokenDeriveRequestFromJSONTyped(json, false);
}

export function TokenDeriveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenDeriveRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'network': json['network'],
        'creatorAccountAddress': json['creator_account_address'],
        'symbol': json['symbol'],
    };
}

export function TokenDeriveRequestToJSON(value?: TokenDeriveRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'network': value.network,
        'creator_account_address': value.creatorAccountAddress,
        'symbol': value.symbol,
    };
}

