/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenAmount
 */
export interface TokenAmount {
    /**
     * 
     * @type {string}
     * @memberof TokenAmount
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof TokenAmount
     */
    rri: string;
}

export function TokenAmountFromJSON(json: any): TokenAmount {
    return TokenAmountFromJSONTyped(json, false);
}

export function TokenAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenAmount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
        'rri': json['rri'],
    };
}

export function TokenAmountToJSON(value?: TokenAmount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'rri': value.rri,
    };
}

