/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LedgerState,
    LedgerStateFromJSON,
    LedgerStateFromJSONTyped,
    LedgerStateToJSON,
    Token,
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
} from './';

/**
 * 
 * @export
 * @interface TokenInfoResponse
 */
export interface TokenInfoResponse {
    /**
     * 
     * @type {LedgerState}
     * @memberof TokenInfoResponse
     */
    ledgerState: LedgerState;
    /**
     * 
     * @type {Array<Token>}
     * @memberof TokenInfoResponse
     */
    token: Array<Token>;
}

export function TokenInfoResponseFromJSON(json: any): TokenInfoResponse {
    return TokenInfoResponseFromJSONTyped(json, false);
}

export function TokenInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ledgerState': LedgerStateFromJSON(json['ledger_state']),
        'token': ((json['token'] as Array<any>).map(TokenFromJSON)),
    };
}

export function TokenInfoResponseToJSON(value?: TokenInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ledger_state': LedgerStateToJSON(value.ledgerState),
        'token': ((value.token as Array<any>).map(TokenToJSON)),
    };
}

