/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TokenAmount,
    TokenAmountFromJSON,
    TokenAmountFromJSONTyped,
    TokenAmountToJSON,
    TransactionBuildResult,
    TransactionBuildResultFromJSON,
    TransactionBuildResultFromJSONTyped,
    TransactionBuildResultToJSON,
    TransactionBuildSuccessAllOf,
    TransactionBuildSuccessAllOfFromJSON,
    TransactionBuildSuccessAllOfFromJSONTyped,
    TransactionBuildSuccessAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface TransactionBuildSuccess
 */
export interface TransactionBuildSuccess extends TransactionBuildResult {
    /**
     * 
     * @type {TokenAmount}
     * @memberof TransactionBuildSuccess
     */
    fee: TokenAmount;
    /**
     * 
     * @type {string}
     * @memberof TransactionBuildSuccess
     */
    unsignedTransaction: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionBuildSuccess
     */
    payloadToSign: string;
}

export function TransactionBuildSuccessFromJSON(json: any): TransactionBuildSuccess {
    return TransactionBuildSuccessFromJSONTyped(json, false);
}

export function TransactionBuildSuccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionBuildSuccess {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...TransactionBuildResultFromJSONTyped(json, ignoreDiscriminator),
        'fee': TokenAmountFromJSON(json['fee']),
        'unsignedTransaction': json['unsigned_transaction'],
        'payloadToSign': json['payload_to_sign'],
    };
}

export function TransactionBuildSuccessToJSON(value?: TransactionBuildSuccess | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...TransactionBuildResultToJSON(value),
        'fee': TokenAmountToJSON(value.fee),
        'unsigned_transaction': value.unsignedTransaction,
        'payload_to_sign': value.payloadToSign,
    };
}

