/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TokenAmount,
    TokenAmountFromJSON,
    TokenAmountFromJSONTyped,
    TokenAmountToJSON,
} from './';

/**
 * 
 * @export
 * @interface TransactionBuildSuccessAllOf
 */
export interface TransactionBuildSuccessAllOf {
    /**
     * 
     * @type {TokenAmount}
     * @memberof TransactionBuildSuccessAllOf
     */
    fee: TokenAmount;
    /**
     * 
     * @type {string}
     * @memberof TransactionBuildSuccessAllOf
     */
    unsignedTransaction: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionBuildSuccessAllOf
     */
    payloadToSign: string;
}

export function TransactionBuildSuccessAllOfFromJSON(json: any): TransactionBuildSuccessAllOf {
    return TransactionBuildSuccessAllOfFromJSONTyped(json, false);
}

export function TransactionBuildSuccessAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionBuildSuccessAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fee': TokenAmountFromJSON(json['fee']),
        'unsignedTransaction': json['unsigned_transaction'],
        'payloadToSign': json['payload_to_sign'],
    };
}

export function TransactionBuildSuccessAllOfToJSON(value?: TransactionBuildSuccessAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fee': TokenAmountToJSON(value.fee),
        'unsigned_transaction': value.unsignedTransaction,
        'payload_to_sign': value.payloadToSign,
    };
}

