/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TokenAmount,
    TokenAmountFromJSON,
    TokenAmountFromJSONTyped,
    TokenAmountToJSON,
} from './';

/**
 * 
 * @export
 * @interface TransferTokensAllOf
 */
export interface TransferTokensAllOf {
    /**
     * 
     * @type {string}
     * @memberof TransferTokensAllOf
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof TransferTokensAllOf
     */
    to: string;
    /**
     * 
     * @type {TokenAmount}
     * @memberof TransferTokensAllOf
     */
    amount: TokenAmount;
}

export function TransferTokensAllOfFromJSON(json: any): TransferTokensAllOf {
    return TransferTokensAllOfFromJSONTyped(json, false);
}

export function TransferTokensAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferTokensAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'amount': TokenAmountFromJSON(json['amount']),
    };
}

export function TransferTokensAllOfToJSON(value?: TransferTokensAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': value.from,
        'to': value.to,
        'amount': TokenAmountToJSON(value.amount),
    };
}

