/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Action,
    ActionFromJSON,
    ActionFromJSONTyped,
    ActionToJSON,
    TokenAmount,
    TokenAmountFromJSON,
    TokenAmountFromJSONTyped,
    TokenAmountToJSON,
    UnstakeTokensAllOf,
    UnstakeTokensAllOfFromJSON,
    UnstakeTokensAllOfFromJSONTyped,
    UnstakeTokensAllOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface UnstakeTokens
 */
export interface UnstakeTokens extends Action {
    /**
     * 
     * @type {string}
     * @memberof UnstakeTokens
     */
    from: string;
    /**
     * 
     * @type {string}
     * @memberof UnstakeTokens
     */
    to: string;
    /**
     * 
     * @type {TokenAmount}
     * @memberof UnstakeTokens
     */
    amount: TokenAmount;
}

export function UnstakeTokensFromJSON(json: any): UnstakeTokens {
    return UnstakeTokensFromJSONTyped(json, false);
}

export function UnstakeTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnstakeTokens {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...ActionFromJSONTyped(json, ignoreDiscriminator),
        'from': json['from'],
        'to': json['to'],
        'amount': TokenAmountFromJSON(json['amount']),
    };
}

export function UnstakeTokensToJSON(value?: UnstakeTokens | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...ActionToJSON(value),
        'from': value.from,
        'to': value.to,
        'amount': TokenAmountToJSON(value.amount),
    };
}

