/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EpochRange
 */
export interface EpochRange {
    /**
     * 
     * @type {number}
     * @memberof EpochRange
     */
    from: number;
    /**
     * 
     * @type {number}
     * @memberof EpochRange
     */
    to: number;
}

export function EpochRangeFromJSON(json: any): EpochRange {
    return EpochRangeFromJSONTyped(json, false);
}

export function EpochRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EpochRange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
    };
}

export function EpochRangeToJSON(value?: EpochRange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': value.from,
        'to': value.to,
    };
}

