/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TokenAmount,
    TokenAmountFromJSON,
    TokenAmountFromJSONTyped,
    TokenAmountToJSON,
    ValidatorIdentifier,
    ValidatorIdentifierFromJSON,
    ValidatorIdentifierFromJSONTyped,
    ValidatorIdentifierToJSON,
} from './';

/**
 * 
 * @export
 * @interface MintTokensAllOf
 */
export interface MintTokensAllOf {
    /**
     * 
     * @type {ValidatorIdentifier}
     * @memberof MintTokensAllOf
     */
    to: ValidatorIdentifier;
    /**
     * 
     * @type {TokenAmount}
     * @memberof MintTokensAllOf
     */
    amount: TokenAmount;
}

export function MintTokensAllOfFromJSON(json: any): MintTokensAllOf {
    return MintTokensAllOfFromJSONTyped(json, false);
}

export function MintTokensAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): MintTokensAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'to': ValidatorIdentifierFromJSON(json['to']),
        'amount': TokenAmountFromJSON(json['amount']),
    };
}

export function MintTokensAllOfToJSON(value?: MintTokensAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'to': ValidatorIdentifierToJSON(value.to),
        'amount': TokenAmountToJSON(value.amount),
    };
}

