/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountIdentifier,
    AccountIdentifierFromJSON,
    AccountIdentifierFromJSONTyped,
    AccountIdentifierToJSON,
    TokenAmount,
    TokenAmountFromJSON,
    TokenAmountFromJSONTyped,
    TokenAmountToJSON,
    ValidatorIdentifier,
    ValidatorIdentifierFromJSON,
    ValidatorIdentifierFromJSONTyped,
    ValidatorIdentifierToJSON,
} from './';

/**
 * 
 * @export
 * @interface UnstakeTokensAllOf
 */
export interface UnstakeTokensAllOf {
    /**
     * 
     * @type {ValidatorIdentifier}
     * @memberof UnstakeTokensAllOf
     */
    from: ValidatorIdentifier;
    /**
     * 
     * @type {AccountIdentifier}
     * @memberof UnstakeTokensAllOf
     */
    to: AccountIdentifier;
    /**
     * 
     * @type {TokenAmount}
     * @memberof UnstakeTokensAllOf
     */
    amount: TokenAmount;
}

export function UnstakeTokensAllOfFromJSON(json: any): UnstakeTokensAllOf {
    return UnstakeTokensAllOfFromJSONTyped(json, false);
}

export function UnstakeTokensAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnstakeTokensAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': ValidatorIdentifierFromJSON(json['from']),
        'to': AccountIdentifierFromJSON(json['to']),
        'amount': TokenAmountFromJSON(json['amount']),
    };
}

export function UnstakeTokensAllOfToJSON(value?: UnstakeTokensAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': ValidatorIdentifierToJSON(value.from),
        'to': AccountIdentifierToJSON(value.to),
        'amount': TokenAmountToJSON(value.amount),
    };
}

