/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ValidatorIdentifier,
    ValidatorIdentifierFromJSON,
    ValidatorIdentifierFromJSONTyped,
    ValidatorIdentifierToJSON,
} from './';

/**
 * 
 * @export
 * @interface ValidatorInfoRequest
 */
export interface ValidatorInfoRequest {
    /**
     * 
     * @type {string}
     * @memberof ValidatorInfoRequest
     */
    network: string;
    /**
     * 
     * @type {ValidatorIdentifier}
     * @memberof ValidatorInfoRequest
     */
    validatorIdentifier: ValidatorIdentifier;
}

export function ValidatorInfoRequestFromJSON(json: any): ValidatorInfoRequest {
    return ValidatorInfoRequestFromJSONTyped(json, false);
}

export function ValidatorInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatorInfoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'network': json['network'],
        'validatorIdentifier': ValidatorIdentifierFromJSON(json['validator_identifier']),
    };
}

export function ValidatorInfoRequestToJSON(value?: ValidatorInfoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'network': value.network,
        'validator_identifier': ValidatorIdentifierToJSON(value.validatorIdentifier),
    };
}

