/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidatorIdentifier
 */
export interface ValidatorIdentifier {
    /**
     * 
     * @type {string}
     * @memberof ValidatorIdentifier
     */
    address: string;
}

export function ValidatorIdentifierFromJSON(json: any): ValidatorIdentifier {
    return ValidatorIdentifierFromJSONTyped(json, false);
}

export function ValidatorIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatorIdentifier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
    };
}

export function ValidatorIdentifierToJSON(value?: ValidatorIdentifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
    };
}

