/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
	TokenAmount,
	TokenAmountFromJSON,
	TokenAmountFromJSONTyped,
	TokenAmountToJSON,
	ValidatorIdentifier,
	ValidatorIdentifierFromJSON,
	ValidatorIdentifierFromJSONTyped,
	ValidatorIdentifierToJSON,
} from '.'

/**
 *
 * @export
 * @interface AccountUnstakeEntry
 */
export interface AccountUnstakeEntry {
	/**
	 *
	 * @type {ValidatorIdentifier}
	 * @memberof AccountUnstakeEntry
	 */
	validatorIdentifier: ValidatorIdentifier
	/**
	 *
	 * @type {TokenAmount}
	 * @memberof AccountUnstakeEntry
	 */
	unstakingAmount: TokenAmount
	/**
	 *
	 * @type {number}
	 * @memberof AccountUnstakeEntry
	 */
	epochsUntilUnlocked: number
}

export function AccountUnstakeEntryFromJSON(json: any): AccountUnstakeEntry {
	return AccountUnstakeEntryFromJSONTyped(json, false)
}

export function AccountUnstakeEntryFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): AccountUnstakeEntry {
	if (json === undefined || json === null) {
		return json
	}
	return {
		validatorIdentifier: ValidatorIdentifierFromJSON(
			json['validator_identifier'],
		),
		unstakingAmount: TokenAmountFromJSON(json['unstaking_amount']),
		epochsUntilUnlocked: json['epochs_until_unlocked'],
	}
}

export function AccountUnstakeEntryToJSON(
	value?: AccountUnstakeEntry | null,
): any {
	if (value === undefined) {
		return undefined
	}
	if (value === null) {
		return null
	}
	return {
		validator_identifier: ValidatorIdentifierToJSON(
			value.validatorIdentifier,
		),
		unstaking_amount: TokenAmountToJSON(value.unstakingAmount),
		epochs_until_unlocked: value.epochsUntilUnlocked,
	}
}
