/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountIdentifier
 */
export interface AccountIdentifier {
    /**
     * 
     * @type {string}
     * @memberof AccountIdentifier
     */
    address: string;
}

export function AccountIdentifierFromJSON(json: any): AccountIdentifier {
    return AccountIdentifierFromJSONTyped(json, false);
}

export function AccountIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountIdentifier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
    };
}

export function AccountIdentifierToJSON(value?: AccountIdentifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
    };
}

