/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
	BurnTokensFromJSONTyped,
	MintTokensFromJSONTyped,
	StakeTokensFromJSONTyped,
	TransferTokensFromJSONTyped,
	UnstakeTokensFromJSONTyped,
} from '.'

/**
 *
 * @export
 * @interface Action
 */
export interface Action {
	/**
	 *
	 * @type {string}
	 * @memberof Action
	 */
	type: string
}

export function ActionFromJSON(json: any): Action {
	return ActionFromJSONTyped(json, false)
}

export function ActionFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): Action {
	if (json === undefined || json === null) {
		return json
	}
	if (!ignoreDiscriminator) {
		if (json['type'] === 'BurnTokens') {
			return BurnTokensFromJSONTyped(json, true)
		}
		if (json['type'] === 'MintTokens') {
			return MintTokensFromJSONTyped(json, true)
		}
		if (json['type'] === 'StakeTokens') {
			return StakeTokensFromJSONTyped(json, true)
		}
		if (json['type'] === 'TransferTokens') {
			return TransferTokensFromJSONTyped(json, true)
		}
		if (json['type'] === 'UnstakeTokens') {
			return UnstakeTokensFromJSONTyped(json, true)
		}
	}
	return {
		type: json['type'],
	}
}

export function ActionToJSON(value?: Action | null): any {
	if (value === undefined) {
		return undefined
	}
	if (value === null) {
		return null
	}
	return {
		type: value.type,
	}
}
