/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
	MessageTooLongErrorAllOf,
	MessageTooLongErrorAllOfFromJSON,
	MessageTooLongErrorAllOfFromJSONTyped,
	MessageTooLongErrorAllOfToJSON,
	TransactionBuildError,
	TransactionBuildErrorFromJSON,
	TransactionBuildErrorFromJSONTyped,
	TransactionBuildErrorToJSON,
} from '.'

/**
 *
 * @export
 * @interface MessageTooLongError
 */
export interface MessageTooLongError extends TransactionBuildError {
	/**
	 *
	 * @type {number}
	 * @memberof MessageTooLongError
	 */
	lengthLimit: number
	/**
	 *
	 * @type {number}
	 * @memberof MessageTooLongError
	 */
	attemptedLength: number
}

export function MessageTooLongErrorFromJSON(json: any): MessageTooLongError {
	return MessageTooLongErrorFromJSONTyped(json, false)
}

export function MessageTooLongErrorFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): MessageTooLongError {
	if (json === undefined || json === null) {
		return json
	}
	return {
		...TransactionBuildErrorFromJSONTyped(json, ignoreDiscriminator),
		lengthLimit: json['length_limit'],
		attemptedLength: json['attempted_length'],
	}
}

export function MessageTooLongErrorToJSON(
	value?: MessageTooLongError | null,
): any {
	if (value === undefined) {
		return undefined
	}
	if (value === null) {
		return null
	}
	return {
		...TransactionBuildErrorToJSON(value),
		length_limit: value.lengthLimit,
		attempted_length: value.attemptedLength,
	}
}
