/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
	NotEnoughResourcesErrorAllOf,
	NotEnoughResourcesErrorAllOfFromJSON,
	NotEnoughResourcesErrorAllOfFromJSONTyped,
	NotEnoughResourcesErrorAllOfToJSON,
	TransactionBuildError,
	TransactionBuildErrorFromJSON,
	TransactionBuildErrorFromJSONTyped,
	TransactionBuildErrorToJSON,
} from '.'

/**
 *
 * @export
 * @interface NotEnoughResourcesError
 */
export interface NotEnoughResourcesError extends TransactionBuildError {
	/**
	 *
	 * @type {string}
	 * @memberof NotEnoughResourcesError
	 */
	requestedAmount: string
	/**
	 *
	 * @type {string}
	 * @memberof NotEnoughResourcesError
	 */
	availableAmount: string
}

export function NotEnoughResourcesErrorFromJSON(
	json: any,
): NotEnoughResourcesError {
	return NotEnoughResourcesErrorFromJSONTyped(json, false)
}

export function NotEnoughResourcesErrorFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): NotEnoughResourcesError {
	if (json === undefined || json === null) {
		return json
	}
	return {
		...TransactionBuildErrorFromJSONTyped(json, ignoreDiscriminator),
		requestedAmount: json['requested_amount'],
		availableAmount: json['available_amount'],
	}
}

export function NotEnoughResourcesErrorToJSON(
	value?: NotEnoughResourcesError | null,
): any {
	if (value === undefined) {
		return undefined
	}
	if (value === null) {
		return null
	}
	return {
		...TransactionBuildErrorToJSON(value),
		requested_amount: value.requestedAmount,
		available_amount: value.availableAmount,
	}
}
