/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
	AccountIdentifier,
	AccountIdentifierFromJSON,
	AccountIdentifierFromJSONTyped,
	AccountIdentifierToJSON,
} from '.'

/**
 *
 * @export
 * @interface NotValidatorOwnerErrorAllOf
 */
export interface NotValidatorOwnerErrorAllOf {
	/**
	 *
	 * @type {AccountIdentifier}
	 * @memberof NotValidatorOwnerErrorAllOf
	 */
	owner: AccountIdentifier
	/**
	 *
	 * @type {AccountIdentifier}
	 * @memberof NotValidatorOwnerErrorAllOf
	 */
	user: AccountIdentifier
}

export function NotValidatorOwnerErrorAllOfFromJSON(
	json: any,
): NotValidatorOwnerErrorAllOf {
	return NotValidatorOwnerErrorAllOfFromJSONTyped(json, false)
}

export function NotValidatorOwnerErrorAllOfFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): NotValidatorOwnerErrorAllOf {
	if (json === undefined || json === null) {
		return json
	}
	return {
		owner: AccountIdentifierFromJSON(json['owner']),
		user: AccountIdentifierFromJSON(json['user']),
	}
}

export function NotValidatorOwnerErrorAllOfToJSON(
	value?: NotValidatorOwnerErrorAllOf | null,
): any {
	if (value === undefined) {
		return undefined
	}
	if (value === null) {
		return null
	}
	return {
		owner: AccountIdentifierToJSON(value.owner),
		user: AccountIdentifierToJSON(value.user),
	}
}
