/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
	LedgerState,
	LedgerStateFromJSON,
	LedgerStateFromJSONTyped,
	LedgerStateToJSON,
	Token,
	TokenFromJSON,
	TokenFromJSONTyped,
	TokenToJSON,
} from '.'

/**
 *
 * @export
 * @interface TokenNativeResponse
 */
export interface TokenNativeResponse {
	/**
	 *
	 * @type {LedgerState}
	 * @memberof TokenNativeResponse
	 */
	ledgerState: LedgerState
	/**
	 *
	 * @type {Array<Token>}
	 * @memberof TokenNativeResponse
	 */
	token: Array<Token>
}

export function TokenNativeResponseFromJSON(json: any): TokenNativeResponse {
	return TokenNativeResponseFromJSONTyped(json, false)
}

export function TokenNativeResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): TokenNativeResponse {
	if (json === undefined || json === null) {
		return json
	}
	return {
		ledgerState: LedgerStateFromJSON(json['ledger_state']),
		token: (json['token'] as Array<any>).map(TokenFromJSON),
	}
}

export function TokenNativeResponseToJSON(
	value?: TokenNativeResponse | null,
): any {
	if (value === undefined) {
		return undefined
	}
	if (value === null) {
		return null
	}
	return {
		ledger_state: LedgerStateToJSON(value.ledgerState),
		token: (value.token as Array<any>).map(TokenToJSON),
	}
}
