/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenNativeRequest
 */
export interface TokenNativeRequest {
    /**
     * 
     * @type {string}
     * @memberof TokenNativeRequest
     */
    network: string;
}

export function TokenNativeRequestFromJSON(json: any): TokenNativeRequest {
    return TokenNativeRequestFromJSONTyped(json, false);
}

export function TokenNativeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenNativeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'network': json['network'],
    };
}

export function TokenNativeRequestToJSON(value?: TokenNativeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'network': value.network,
    };
}

