/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
	TransactionIdentifier,
	TransactionIdentifierFromJSON,
	TransactionIdentifierFromJSONTyped,
	TransactionIdentifierToJSON,
} from '.'

/**
 *
 * @export
 * @interface TransactionSubmitResponse
 */
export interface TransactionSubmitResponse {
	/**
	 *
	 * @type {TransactionIdentifier}
	 * @memberof TransactionSubmitResponse
	 */
	transactionIdentifier: TransactionIdentifier
}

export function TransactionSubmitResponseFromJSON(
	json: any,
): TransactionSubmitResponse {
	return TransactionSubmitResponseFromJSONTyped(json, false)
}

export function TransactionSubmitResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): TransactionSubmitResponse {
	if (json === undefined || json === null) {
		return json
	}
	return {
		transactionIdentifier: TransactionIdentifierFromJSON(
			json['transaction_identifier'],
		),
	}
}

export function TransactionSubmitResponseToJSON(
	value?: TransactionSubmitResponse | null,
): any {
	if (value === undefined) {
		return undefined
	}
	if (value === null) {
		return null
	}
	return {
		transaction_identifier: TransactionIdentifierToJSON(
			value.transactionIdentifier,
		),
	}
}
