/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
	TransactionBuildError,
	TransactionBuildErrorFromJSON,
	TransactionBuildErrorFromJSONTyped,
	TransactionBuildErrorToJSON,
	TransactionBuildResponse,
	TransactionBuildResponseFromJSON,
	TransactionBuildResponseFromJSONTyped,
	TransactionBuildResponseToJSON,
	TransactionBuildResponseErrorAllOf,
	TransactionBuildResponseErrorAllOfFromJSON,
	TransactionBuildResponseErrorAllOfFromJSONTyped,
	TransactionBuildResponseErrorAllOfToJSON,
} from '.'

/**
 *
 * @export
 * @interface TransactionBuildResponseError
 */
export interface TransactionBuildResponseError
	extends TransactionBuildResponse {
	/**
	 *
	 * @type {TransactionBuildError}
	 * @memberof TransactionBuildResponseError
	 */
	error: TransactionBuildError
}

export function TransactionBuildResponseErrorFromJSON(
	json: any,
): TransactionBuildResponseError {
	return TransactionBuildResponseErrorFromJSONTyped(json, false)
}

export function TransactionBuildResponseErrorFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): TransactionBuildResponseError {
	if (json === undefined || json === null) {
		return json
	}
	return {
		...TransactionBuildResponseFromJSONTyped(json, ignoreDiscriminator),
		error: TransactionBuildErrorFromJSON(json['error']),
	}
}

export function TransactionBuildResponseErrorToJSON(
	value?: TransactionBuildResponseError | null,
): any {
	if (value === undefined) {
		return undefined
	}
	if (value === null) {
		return null
	}
	return {
		...TransactionBuildResponseToJSON(value),
		error: TransactionBuildErrorToJSON(value.error),
	}
}
