/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
	TransactionBuildResponseErrorFromJSONTyped,
	TransactionBuildResponseSuccessFromJSONTyped,
} from '.'

/**
 *
 * @export
 * @interface TransactionBuildResponse
 */
export interface TransactionBuildResponse {
	/**
	 *
	 * @type {string}
	 * @memberof TransactionBuildResponse
	 */
	type: string
}

export function TransactionBuildResponseFromJSON(
	json: any,
): TransactionBuildResponse {
	return TransactionBuildResponseFromJSONTyped(json, false)
}

export function TransactionBuildResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): TransactionBuildResponse {
	if (json === undefined || json === null) {
		return json
	}
	if (!ignoreDiscriminator) {
		if (json['type'] === 'TransactionBuildResponseError') {
			return TransactionBuildResponseErrorFromJSONTyped(json, true)
		}
		if (json['type'] === 'TransactionBuildResponseSuccess') {
			return TransactionBuildResponseSuccessFromJSONTyped(json, true)
		}
	}
	return {
		type: json['type'],
	}
}

export function TransactionBuildResponseToJSON(
	value?: TransactionBuildResponse | null,
): any {
	if (value === undefined) {
		return undefined
	}
	if (value === null) {
		return null
	}
	return {
		type: value.type,
	}
}
