/* tslint:disable */
/* eslint-disable */
/**
 * Radix Gateway API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
	EpochRange,
	EpochRangeFromJSON,
	EpochRangeFromJSONTyped,
	EpochRangeToJSON,
} from '.'

/**
 *
 * @export
 * @interface ValidatorUptime
 */
export interface ValidatorUptime {
	/**
	 *
	 * @type {EpochRange}
	 * @memberof ValidatorUptime
	 */
	epochRange: EpochRange
	/**
	 *
	 * @type {string}
	 * @memberof ValidatorUptime
	 */
	uptimePercentage: string
	/**
	 *
	 * @type {number}
	 * @memberof ValidatorUptime
	 */
	proposalsMissed: number
	/**
	 *
	 * @type {number}
	 * @memberof ValidatorUptime
	 */
	proposalsCompleted: number
}

export function ValidatorUptimeFromJSON(json: any): ValidatorUptime {
	return ValidatorUptimeFromJSONTyped(json, false)
}

export function ValidatorUptimeFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean,
): ValidatorUptime {
	if (json === undefined || json === null) {
		return json
	}
	return {
		epochRange: EpochRangeFromJSON(json['epoch_range']),
		uptimePercentage: json['uptime_percentage'],
		proposalsMissed: json['proposals_missed'],
		proposalsCompleted: json['proposals_completed'],
	}
}

export function ValidatorUptimeToJSON(value?: ValidatorUptime | null): any {
	if (value === undefined) {
		return undefined
	}
	if (value === null) {
		return null
	}
	return {
		epoch_range: EpochRangeToJSON(value.epochRange),
		uptime_percentage: value.uptimePercentage,
		proposals_missed: value.proposalsMissed,
		proposals_completed: value.proposalsCompleted,
	}
}
